# Generated by Django 5.1.7 on 2025-03-14 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("company_size", models.IntegerField(max_length=200)),
                ("revenue_size", models.IntegerField(max_length=200)),
                ("history", models.BooleanField()),
                ("website_url", models.CharField(max_length=200)),
                ("social_media", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AT", "Attracted"),
                            ("CO", "Contacted"),
                            ("QU", "Qualified"),
                            ("PS", "Proposal Sent"),
                            ("AS", "Application Submitted"),
                            ("WC", "Won/Closed"),
                        ],
                        max_length=2,
                    ),
                ),
                ("time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email", models.EmailField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("interest_id", models.AutoField(primary_key=True, serialize=False)),
                ("interest_name", models.CharField(max_length=200)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.client"
                    ),
                ),
            ],
        ),
    ]
