# Generated by Django 5.2 on 2025-04-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
