# Generated by Django 5.2 on 2025-04-10 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_company_website_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name_plural": "Statuses"},
        ),
        migrations.AddField(
            model_name="status",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.client",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="company_size",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="company",
            name="revenue_size",
            field=models.IntegerField(),
        ),
    ]
