# Generated by Django 5.2 on 2025-04-20 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0003_alter_status_options_status_client_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                (
                    "type_of_organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "country_of_operation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("organization_size", models.IntegerField()),
                ("revenue_size", models.IntegerField()),
                ("history", models.BooleanField()),
                ("website_url", models.URLField(blank=True, null=True)),
                ("social_media", models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name="client",
            name="company",
        ),
        migrations.RemoveField(
            model_name="interest",
            name="client",
        ),
        migrations.AddField(
            model_name="client",
            name="organization",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.organization",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("sector_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("tourism", "Tourism"),
                            ("culture", "Culture"),
                            ("sustainability", "Sustainability"),
                            ("education", "Education"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.client"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Interest",
        ),
    ]
