# Generated by Django 5.2 on 2025-04-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0004_organization_remove_client_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="status",
            name="status",
            field=models.CharField(
                choices=[
                    ("AT", "Attracted"),
                    ("CO", "Contacted"),
                    ("IT", "Interested"),
                    ("QU", "Qualified"),
                    ("RS", "Registered"),
                    ("AS", "Call Application Submitted"),
                ],
                max_length=2,
            ),
        ),
    ]
