# Generated by Django 5.2 on 2025-04-22 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0005_alter_status_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="history",
        ),
    ]
